#ifndef NeuMaterials_hh_
#define NeuMaterials_hh_

#include "G4Material.hh"
#include "G4Isotope.hh"
#include "G4Element.hh"

#include "NeuElement.hh"

/*!
	\file NeuMaterials.hh
	\brief Header file containing the definitions of material compositions used in rock and concrete

	\author Kevin Wierman
*/

namespace NeuFlux
{
	/*!
	  \class NeuConcrete
	 
	  \ingroup NeuFlux
	 
	  \brief Chemical and isotopic definitions of the composition of concrete
	 
	  \warning This composition was taken from a page generated by concrete company proponates
	 
	  \author Kevin Wierman
	 
	  \version 1.0 
	 
	  \date  Oct 1, 2013
	 
	  \contact kwierman@email.unc.edu
	 
	*/
	class NeuConcrete : public G4Material
	{
		public:
			/*!
				The only constructor that should be used with this class.
				This data came from an unknown source

			*/
			NeuConcrete() : G4Material( "concrete Approximation", 2.4*g/cm3, 2)
			{
				natO = new NeuOxygen();
				natSi = new NeuSilicon();
		   		this->AddElement( (G4Element*) natSi, 1 );
   				this->AddElement( (G4Element*) natO, 2 );
			}
			virtual ~NeuConcrete()
			{
				delete natO;
				delete natSi;
			}

		private:
			NeuOxygen* natO;
			NeuSilicon* natSi;
	};

	/*!
	  \class NeuRock
	 
	  \ingroup NeuFlux
	 
	  \brief Chemical and isotopic definitions of the composition of rocks in South Dakota
	 
	    The chemical composition is as follows:

				87.05 	SiO3
				6.560 	Al203
				0.840	Fe203
				1.243	MgO
				0.950	CaO
				3.008	Na2O

		Given this, the Natural isotopic abuundances are


	  \note Source: Geological Survey Professional Paper, Volume 561, "Chemical Composition of Sedimentary Rocks in Colorado, Kansas, Montana, Nebraska, North Dakota, South Dakota, Wyoming"
	  
	  http://books.google.com/books?id=Gk_wAAAAMAAJ&lpg=PA1&ots=ejVIkWh5AQ&dq=chemical%20composition%20of%20rocks%20in%20south%20dakota&pg=PA12#v=onepage&q=chemical%20composition%20of%20rocks%20in%20south%20dakota&f=false
	  	
	  http://www.chem.ualberta.ca/~massspec/atomic_mass_abund.pdf

	  \warning High variances in rock composition make this an approximation
	 
	  \author Kevin Wierman
	 
	  \version 1.0 
	  \revision 1.0 
	 
	  \date  Tue Nov 20 12::33:51 2012 $
	 
	  Contact: kwierman@email.unc.edu
	 
	  Created on: Tue Oct 1 8:39:37 2013
	 
	 */
	class NeuRock : public G4Material
	{
		public:
			/*!
				The only constructor that should be used with this class.
				This data came from an unknown source
			*/
			NeuRock() : G4Material( "rock Approximation", 3200*g/cm3, 10, kStateSolid)
			{
				natO = new NeuOxygen;
				natSi = new NeuSilicon;
				natAl = new NeuAluminum;
				natFe = new NeuIron;

				natCa = new NeuCalcium;
				natNa = new NeuSodium;
				natK = new NeuPotassium;
				natMg = new NeuMagnesium;
				
				natH = new NeuHydrogen;
				natC = new NeuCarbon;

				/*

				this->AddElement( (G4Element*) natO,0.331);
				this->AddElement( (G4Element*) natSi,0.277);
				this->AddElement( (G4Element*) natAl,0.081);
				this->AddElement( (G4Element*) natFe,0.050);
				this->AddElement( (G4Element*) natCa,0.036);
				this->AddElement( (G4Element*) natNa,0.028);
				this->AddElement( (G4Element*) natK,0.026);
				this->AddElement( (G4Element*) natMg,0.021);
				this->AddElement( (G4Element*) natH, 0.10);
				this->AddElement( (G4Element*) natC, 0.05);

				*/
				G4NistManager* man = G4NistManager::Instance();
				G4bool isotopes = false;

				this->AddElement( man->FindOrBuildElement("O" , isotopes),0.331);
				this->AddElement( man->FindOrBuildElement("Si" , isotopes),0.277);
				this->AddElement( man->FindOrBuildElement("Al" , isotopes),0.081);
				this->AddElement( man->FindOrBuildElement("Fe" , isotopes),0.050);
				this->AddElement( man->FindOrBuildElement("Ca" , isotopes),0.036);
				this->AddElement( man->FindOrBuildElement("Na" , isotopes),0.028);
				this->AddElement( man->FindOrBuildElement("K" , isotopes),0.026);
				this->AddElement( man->FindOrBuildElement("Mg" , isotopes),0.021);
				this->AddElement( man->FindOrBuildElement("H" , isotopes), 0.10);
				this->AddElement( man->FindOrBuildElement("C" , isotopes), 0.05);
			}
			virtual ~NeuRock()
			{
				delete natO;
				delete natSi;
				delete natAl;
				delete natFe;
				delete natCa;
				delete natNa;
				delete natK;
				delete natMg;
				delete natH;
				delete natC;
			}

		private:
			NeuHydrogen* natH;
			NeuCarbon* natC;
			NeuOxygen* natO;
			NeuSilicon* natSi;
			NeuAluminum* natAl;
			NeuIron* natFe;
			NeuCalcium* natCa;
			NeuSodium* natNa;
			NeuPotassium* natK;
			NeuMagnesium* natMg;
	};

	class NeuHydroCarbon : public G4Material
	{
		public:
			/*!
				The only constructor that should be used with this class.
				This data came from an unknown source
			*/
			NeuHydroCarbon() : G4Material( "hydrocarbon Approximation", 3200*g/cm3, 2, kStateSolid)
			{
				natC = new NeuCarbon();
				natH = new NeuHydrogen();

		   		this->AddElement( (G4Element*)natC, 2 );
   				this->AddElement( (G4Element*)natH, 4 );
			}
			virtual ~NeuHydroCarbon()
			{

				delete natC;

				delete natH;
			}

		private:
			NeuCarbon* natC;

			NeuHydrogen* natH;
	};
}

#endif

