#ifndef NeuMaterials_hh_
#define NeuMaterials_hh_

#include "G4Material.hh"
#include "G4Isotope.hh"
#include "G4Element.hh"

/*!
	\file NeuMaterials.hh
	\brief Header file containing the definitions of material compositions used in rock and concrete

	\author Kevin Wierman
*/

namespace NeuFlux
{
	/*!
	  \class NeuConcrete
	 
	  \ingroup NeuFlux
	 
	  \brief Chemical and isotopic definitions of the composition of concrete
	 
	  \warning This composition was taken from a page generated by concrete company proponates
	 
	  \author Kevin Wierman
	 
	  \version 1.0 
	  \revision 0.0 
	 
	  \date  Tue Nov 20 12::33:51 2012 $
	 
	  Contact: kwierman@email.unc.edu
	 
	  Created on: Tue Oct 1 8:39:37 2013
	 
	 */
	class NeuConcrete : public G4Material
	{
		public:
			/*!
				The only constructor that should be used with this class.
				This data came from an unknown source

			*/
			NeuConcrete()
			{

				O16 = new G4Isotope( "O16", 8, 16, 15.99491463*g/mole );
	 			O17 = new G4Isotope( "O17", 8, 17, 16.9991312*g/mole );
	 			O18 = new G4Isotope( "O18", 8, 18, 17.9991603*g/mole );

   				Si28 = new G4Isotope( "Si28", 14, 28, 27.9769265325*g/mole );
   				Si29 = new G4Isotope( "Si28", 14, 29, 28.976494700*g/mole );
   				Si30 = new G4Isotope( "Si28", 14, 30, 29.97377017*g/mole );
	
	 			natO = new G4Element( "Natural O", "natO", 3 );
				natO->AddIsotope( O16, 99.757*perCent );
				natO->AddIsotope( O17, 0.038*perCent );
				natO->AddIsotope( O18, 0.205*perCent );

   				natSi = new G4Element( "Natural Si", "natSi", 3 );
   				natSi->AddIsotope( Si28, 92.223*perCent );
   				natSi->AddIsotope( Si29, 4.685*perCent );
   				natSi->AddIsotope( Si30, 3.092*perCent );
	
	
				G4Material( "concrete Approximation", 2.4*g/cm3, 2);
 
		   		this->AddElement( natSi, 1 );
   				this->AddElement( natO, 2 );
			}
			virtual ~NeuConcrete()
			{
				delete O16;
				delete O17;
				delete O18;
				
				delete Si28;
				delete Si29;
				delete Si30;

				delete natO;

				delete natSi;
			}

		private:
			G4Isotope* O16;
			G4Isotope* O17;
			G4Isotope* O18;
			
			G4Isotope* Si28;
			G4Isotope* Si29;
			G4Isotope* Si30;

			G4Element* natO;

			G4Element* natSi;
	};

	/*!
	  \class NeuRock
	 
	  \ingroup NeuFlux
	 
	  \brief Chemical and isotopic definitions of the composition of rocks in South Dakota
	 
	    The chemical composition is as follows:

				87.05 	SiO3
				6.560 	Al203
				0.840	Fe203
				1.243	MgO
				0.950	CaO
				3.008	Na2O

		Given this, the Natural isotopic abuundances are


	  \note Source: Geological Survey Professional Paper, Volume 561, "Chemical Composition of Sedimentary Rocks in Colorado, Kansas, Montana, Nebraska, North Dakota, South Dakota, Wyoming"
	  
	  http://books.google.com/books?id=Gk_wAAAAMAAJ&lpg=PA1&ots=ejVIkWh5AQ&dq=chemical%20composition%20of%20rocks%20in%20south%20dakota&pg=PA12#v=onepage&q=chemical%20composition%20of%20rocks%20in%20south%20dakota&f=false
	  	
	  http://www.chem.ualberta.ca/~massspec/atomic_mass_abund.pdf

	  \warning High variances in rock composition make this an approximation
	 
	  \author Kevin Wierman
	 
	  \version 1.0 
	  \revision 0.0 
	 
	  \date  Tue Nov 20 12::33:51 2012 $
	 
	  Contact: kwierman@email.unc.edu
	 
	  Created on: Tue Oct 1 8:39:37 2013
	 
	 */
	class NeuRock : public G4Material
	{
		public:
			/*!
				The only constructor that should be used with this class.
				This data came from an unknown source

			*/
			NeuRock()
			{

				O16 = new G4Isotope( "O16", 8, 16, 15.99491463*g/mole );
	 			O17 = new G4Isotope( "O17", 8, 17, 16.9991312*g/mole );
	 			O18 = new G4Isotope( "O18", 8, 18, 17.9991603*g/mole );

   				Si28 = new G4Isotope( "Si28", 14, 28, 27.9769265325*g/mole );
   				Si29 = new G4Isotope( "Si28", 14, 29, 28.976494700*g/mole );
   				Si30 = new G4Isotope( "Si28", 14, 30, 29.97377017*g/mole );
	
	 			natO = new G4Element( "Natural O", "natO", 3 );
				natO->AddIsotope( O16, 99.757*perCent );
				natO->AddIsotope( O17, 0.038*perCent );
				natO->AddIsotope( O18, 0.205*perCent );

   				natSi = new G4Element( "Natural Si", "natSi", 3 );
   				natSi->AddIsotope( Si28, 92.223*perCent );
   				natSi->AddIsotope( Si29, 4.685*perCent );
   				natSi->AddIsotope( Si30, 3.092*perCent );
	
	
				G4Material( "concrete Approximation", 2.4*g/cm3, 2);
 
		   		this->AddElement( natSi, 1 );
   				this->AddElement( natO, 2 );
			}
			virtual ~NeuRock()
			{
				delete O16;
				delete O17;
				delete O18;
				
				delete Si28;
				delete Si29;
				delete Si30;

				delete natO;

				delete natSi;
			}

		private:
			G4Isotope* O16;
			G4Isotope* O17;
			G4Isotope* O18;
			
			G4Isotope* Si28;
			G4Isotope* Si29;
			G4Isotope* Si30;

			G4Element* natO;

			G4Element* natSi;
	};
}







#endif